import { createFileRoute } from "@tanstack/react-router";
import { FileDown, FileText, ChevronRight } from "lucide-react";
import { Topbar } from "@/components/wirewise/topbar";
import { envVars } from "@/lib/mock-data";

export const Route = createFileRoute("/app/docs")({
  head: () => ({
    meta: [
      { title: "AI Documentation — WireWise AI" },
      { name: "description", content: "Auto-generated documentation for your project." },
    ],
  }),
  component: DocsPage,
});

const sections = [
  { id: "overview", title: "Project Overview" },
  { id: "architecture", title: "Architecture Summary" },
  { id: "auth", title: "Authentication Flow" },
  { id: "db", title: "Database Structure" },
  { id: "env", title: "Environment Variables" },
  { id: "api", title: "API Connections" },
];

function DocsPage() {
  return (
    <>
      <Topbar title="AI Documentation" subtitle="Auto-generated from your codebase, kept in sync." />
      <div className="flex flex-1 gap-8 p-6 md:p-8">
        <aside className="hidden w-56 shrink-0 lg:block">
          <div className="sticky top-24 space-y-1">
            <div className="mb-2 px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground">On this page</div>
            {sections.map((s) => (
              <a key={s.id} href={`#${s.id}`} className="flex items-center justify-between rounded-xl px-3 py-2 text-sm text-muted-foreground hover:bg-accent hover:text-primary">
                {s.title}
                <ChevronRight className="h-3 w-3 opacity-40" />
              </a>
            ))}
          </div>
        </aside>

        <article className="min-w-0 flex-1 space-y-8">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <div className="text-xs font-medium uppercase tracking-wider text-primary">Finlytics Dashboard</div>
              <h2 className="mt-1 text-3xl font-semibold tracking-tight text-foreground">Technical documentation</h2>
              <p className="mt-1 text-sm text-muted-foreground">Generated by WireWise AI · Updated 2h ago</p>
            </div>
            <div className="flex items-center gap-2">
              <button className="flex items-center gap-2 rounded-xl border border-border bg-card px-3 py-2 text-sm font-medium hover:bg-accent">
                <FileDown className="h-4 w-4" /> Export PDF
              </button>
              <button className="flex items-center gap-2 rounded-xl bg-foreground px-3 py-2 text-sm font-semibold text-white">
                <FileText className="h-4 w-4" /> Export Markdown
              </button>
            </div>
          </div>

          <Section id="overview" title="Project Overview">
            Finlytics is a React 19 SPA served through TanStack Start with SSR disabled on authenticated
            routes. It uses <b>Supabase</b> as the primary backend, delivering realtime analytics for indie
            fintech founders. All user-scoped data is protected with Row Level Security.
          </Section>

          <Section id="architecture" title="Architecture Summary">
            The client talks to Supabase over HTTPS using the publishable key. Server-side logic runs in
            TanStack server functions on Cloudflare Workers. Long-running jobs are offloaded to Supabase
            Edge Functions and observed via structured logs.
          </Section>

          <Section id="auth" title="Authentication Flow">
            Users authenticate using <b>Google OAuth</b>. Supabase generates JWT tokens which are attached
            as bearer tokens to every protected server function call. Sessions rotate every 60 minutes and
            are stored in <code>localStorage</code> under <code>sb-*-auth-token</code>.
          </Section>

          <Section id="db" title="Database Structure">
            <ul className="mt-3 space-y-2 text-sm">
              <li>· <b>users</b> — id, name, email, created_at</li>
              <li>· <b>projects</b> — id, user_id, name, github_url, framework</li>
              <li>· <b>integrations</b> — id, project_id, service_name, status, configuration</li>
              <li>· <b>documentation</b> — id, project_id, summary, architecture_data</li>
              <li>· <b>security_reports</b> — id, project_id, issue, severity, recommendation</li>
            </ul>
          </Section>

          <Section id="env" title="Environment Variables">
            <div className="mt-4 overflow-hidden rounded-2xl border border-border">
              <table className="w-full text-left text-sm">
                <thead className="bg-muted/50 text-xs uppercase tracking-wider text-muted-foreground">
                  <tr>
                    <th className="px-4 py-3">Name</th>
                    <th className="px-4 py-3">Scope</th>
                    <th className="px-4 py-3">Purpose</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-border">
                  {envVars.map((v) => (
                    <tr key={v.name} className="bg-card">
                      <td className="px-4 py-3 font-mono text-xs text-foreground">{v.name}</td>
                      <td className="px-4 py-3">
                        <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium ${v.scope === "Client" ? "bg-accent text-primary" : "bg-amber-50 text-amber-600"}`}>
                          {v.scope}
                        </span>
                      </td>
                      <td className="px-4 py-3 text-xs text-muted-foreground">{v.purpose}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Section>

          <Section id="api" title="API Connections">
            External services: <b>OpenAI</b> (summaries), <b>GitHub REST</b> (repo analysis), <b>Stripe</b>
            (billing webhooks via <code>/api/public/webhooks/stripe</code>).
          </Section>
        </article>
      </div>
    </>
  );
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="scroll-mt-24 rounded-3xl border border-border bg-card p-6 shadow-[var(--shadow-soft)]">
      <h3 className="text-lg font-semibold tracking-tight text-foreground">{title}</h3>
      <div className="mt-3 text-sm leading-relaxed text-muted-foreground [&_b]:text-foreground [&_code]:rounded-md [&_code]:bg-muted [&_code]:px-1 [&_code]:py-0.5 [&_code]:text-[12px] [&_code]:text-foreground">
        {children}
      </div>
    </section>
  );
}