/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppProjectsRouteImport } from './routes/app/projects'
import { Route as AppDocsRouteImport } from './routes/app/docs'
import { Route as AppArchitectureRouteImport } from './routes/app/architecture'
import { Route as AppIntegrationsSupabaseRouteImport } from './routes/app/integrations.supabase'
import { Route as AppIntegrationsGithubRouteImport } from './routes/app/integrations.github'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppArchitectureRoute = AppArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIntegrationsSupabaseRoute = AppIntegrationsSupabaseRouteImport.update({
  id: '/integrations/supabase',
  path: '/integrations/supabase',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppIntegrationsGithubRoute = AppIntegrationsGithubRouteImport.update({
  id: '/integrations/github',
  path: '/integrations/github',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/architecture': typeof AppArchitectureRoute
  '/app/docs': typeof AppDocsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/integrations/github': typeof AppIntegrationsGithubRoute
  '/app/integrations/supabase': typeof AppIntegrationsSupabaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/architecture': typeof AppArchitectureRoute
  '/app/docs': typeof AppDocsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app': typeof AppIndexRoute
  '/app/integrations/github': typeof AppIntegrationsGithubRoute
  '/app/integrations/supabase': typeof AppIntegrationsSupabaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/architecture': typeof AppArchitectureRoute
  '/app/docs': typeof AppDocsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/': typeof AppIndexRoute
  '/app/integrations/github': typeof AppIntegrationsGithubRoute
  '/app/integrations/supabase': typeof AppIntegrationsSupabaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/architecture'
    | '/app/docs'
    | '/app/projects'
    | '/app/'
    | '/app/integrations/github'
    | '/app/integrations/supabase'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app/architecture'
    | '/app/docs'
    | '/app/projects'
    | '/app'
    | '/app/integrations/github'
    | '/app/integrations/supabase'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/architecture'
    | '/app/docs'
    | '/app/projects'
    | '/app/'
    | '/app/integrations/github'
    | '/app/integrations/supabase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/architecture': {
      id: '/app/architecture'
      path: '/architecture'
      fullPath: '/app/architecture'
      preLoaderRoute: typeof AppArchitectureRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/integrations/supabase': {
      id: '/app/integrations/supabase'
      path: '/integrations/supabase'
      fullPath: '/app/integrations/supabase'
      preLoaderRoute: typeof AppIntegrationsSupabaseRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/integrations/github': {
      id: '/app/integrations/github'
      path: '/integrations/github'
      fullPath: '/app/integrations/github'
      preLoaderRoute: typeof AppIntegrationsGithubRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppArchitectureRoute: typeof AppArchitectureRoute
  AppDocsRoute: typeof AppDocsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppIntegrationsGithubRoute: typeof AppIntegrationsGithubRoute
  AppIntegrationsSupabaseRoute: typeof AppIntegrationsSupabaseRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppArchitectureRoute: AppArchitectureRoute,
  AppDocsRoute: AppDocsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppIndexRoute: AppIndexRoute,
  AppIntegrationsGithubRoute: AppIntegrationsGithubRoute,
  AppIntegrationsSupabaseRoute: AppIntegrationsSupabaseRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
